image:
  name: alpine/helm:3.14.4
  entrypoint: ["/bin/sh", "-c"]
stages:
  - lint-helm-chart
  - release-helm-chart
lint-helm:
  stage: lint-helm-chart
  script:
    - helm lint charts/supabase
release-helm:
  stage: release-helm-chart
  script:
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm dependency update charts/supabase
    - helm package charts/supabase
    - helm repo add supabase https://gl.alv.is/api/v4/projects/$CI_PROJECT_ID/packages/helm/devel --username=$CI_DEPLOY_USER --password-stdin<<<$CI_DEPLOY_PASSWORD
    - helm cm-push supabase-0.1.3.tgz supabase
